runtime: nodejs18

# Basic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Resource allocation
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# Environment variables
env_variables:
  NODE_ENV: production
  PORT: 8080

# Health check configuration
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Network configuration
network:
  forwarded_ports:
    - 8080

# Security headers
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
